name: Deploy Service

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      service_name:
        required: false
        type: string
        default: ""

    secrets:
      vm_username:
        required: true
      vm_ip:
        required: true
      ssh_key:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Add PEM Key to SSH Agent
        env:
          PEM_KEY: ${{ secrets.ssh_key }}
        run: |
          echo "$PEM_KEY" > vm_key.pem
          chmod 600 vm_key.pem
          eval "$(ssh-agent -s)"
          ssh-add vm_key.pem

      - name: Deploy Application
        env:
          VM_USERNAME: ${{ secrets.vm_username }}
          VM_IP: ${{ secrets.vm_ip }}
          SERVICE_NAME: ${{ inputs.service_name }}
        run: |
          ssh -o StrictHostKeyChecking=no -i vm_key.pem $VM_USERNAME@$VM_IP << 'EOF'
            cd infra
            TAG=${{ inputs.environment == 'dev' && 'dev' || 'latest' }}

            if [ -n "$SERVICE_NAME" ]; then
              echo "Deploying single service: $SERVICE_NAME"
              docker compose stop $SERVICE_NAME
              docker compose pull $SERVICE_NAME
              docker compose up -d --no-deps --build $SERVICE_NAME
            else
              echo "Deploying full stack"
              docker compose down
              docker compose pull
              docker compose up -d --build
            fi
          EOF

      - name: Cleanup PEM Key
        if: always()
        run: |
          if [ -n "$SSH_AGENT_PID" ]; then
            ssh-agent -k
          fi
          rm -f vm_key.pem
