name: Deploy Service

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      service_name:
        required: false
        type: string
        default: ""

    secrets:
      vm_username:
        required: true
      vm_ip:
        required: true
      ssh_key:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Add PEM Key to SSH Agent
        env:
          PEM_KEY: ${{ secrets.ssh_key }}
        run: |
          echo "$PEM_KEY" > vm_key.pem
          chmod 600 vm_key.pem
          eval "$(ssh-agent -s)"
          ssh-add vm_key.pem

      - name: Deploy Application
        env:
          VM_USERNAME: ${{ secrets.vm_username }}
          VM_IP: ${{ secrets.vm_ip }}
        run: |
          ssh -o StrictHostKeyChecking=no -i vm_key.pem $VM_USERNAME@$VM_IP << 'EOF'
            cd infra
            TAG=${{ inputs.environment == 'dev' && 'dev' || 'latest' }}

            if [ -n "${{ inputs.service_name }}" ]; then
              echo "Deploying single service: ${{ inputs.service_name }}"
              TAG=$TAG docker compose stop ${{ inputs.service_name }}
              TAG=$TAG docker compose pull ${{ inputs.service_name }}
              TAG=$TAG docker compose up -d --no-deps --build ${{ inputs.service_name }}
            else
              echo "Deploying full stack"
              git pull
              TAG=$TAG docker compose down
              TAG=$TAG docker compose pull
              TAG=$TAG docker compose up -d --build
            fi
          EOF

      - name: Cleanup PEM Key
        if: always()
        run: |
          if [ -n "$SSH_AGENT_PID" ]; then
            ssh-agent -k
          fi
          rm -f vm_key.pem
